// File: controller/PemasukanController.java
package controller;

import java.sql.*;import java.util.ArrayList;import java.util.List;import model.Pemasukan;import util.Koneksi;import util.Option;import util.SessionManager;

public class PemasukanController {
    public List<Pemasukan> getAll(java.sql.Date dari, java.sql.Date sampai) throws SQLException { List<Pemasukan> list=new ArrayList<>(); String sql="SELECT p.id_pemasukan,p.tanggal,p.id_siswa,p.id_kategori_pemasukan,p.nominal,p.keterangan,p.id_user_input,COALESCE(s.nama_siswa,'-') nama_siswa,COALESCE(k.nama_kategori,'-') nama_kategori FROM pemasukan p LEFT JOIN siswa s ON p.id_siswa=s.id_siswa LEFT JOIN kategori_pemasukan k ON p.id_kategori_pemasukan=k.id_kategori_pemasukan WHERE (? IS NULL OR p.tanggal>=?) AND (? IS NULL OR p.tanggal<=?) ORDER BY p.tanggal DESC,p.id_pemasukan DESC"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ ps.setDate(1,dari);ps.setDate(2,dari);ps.setDate(3,sampai);ps.setDate(4,sampai); try(ResultSet rs=ps.executeQuery()){ while(rs.next()) list.add(new Pemasukan(rs.getInt(1),rs.getDate(2),(Integer)rs.getObject(3),rs.getInt(4),rs.getDouble(5),rs.getString(6),rs.getInt(7),rs.getString(8),rs.getString(9))); }} return list; }
    public List<Pemasukan> getAll() throws SQLException { return getAll(null,null); }
    public void insert(Pemasukan p) throws SQLException { p.setIdUserInput(SessionManager.getInstance().getCurrentUserId()); String sql="INSERT INTO pemasukan(tanggal,id_siswa,id_kategori_pemasukan,nominal,keterangan,id_user_input) VALUES(?,?,?,?,?,?)"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ fill(ps,p); ps.setInt(6,p.getIdUserInput()); ps.executeUpdate(); } AuditLogger.log(p.getIdUserInput(),"INSERT PEMASUKAN",p.getKeterangan()+" nominal "+p.getNominal()); }
    public void update(Pemasukan p) throws SQLException { String sql="UPDATE pemasukan SET tanggal=?,id_siswa=?,id_kategori_pemasukan=?,nominal=?,keterangan=? WHERE id_pemasukan=?"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ fill(ps,p); ps.setInt(6,p.getIdPemasukan()); ps.executeUpdate(); } AuditLogger.log(SessionManager.getInstance().getCurrentUserId(),"UPDATE PEMASUKAN","ID "+p.getIdPemasukan()); }
    public void delete(int id) throws SQLException { try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM pemasukan WHERE id_pemasukan=?")){ ps.setInt(1,id); ps.executeUpdate(); } AuditLogger.log(SessionManager.getInstance().getCurrentUserId(),"DELETE PEMASUKAN","ID "+id); }
    private void fill(PreparedStatement ps,Pemasukan p)throws SQLException{ ps.setDate(1,p.getTanggal()); if(p.getIdSiswa()==null||p.getIdSiswa()<=0) ps.setNull(2,Types.INTEGER); else ps.setInt(2,p.getIdSiswa()); ps.setInt(3,p.getIdKategoriPemasukan()); ps.setDouble(4,p.getNominal()); ps.setString(5,p.getKeterangan()); }
    public List<Option> getKategoriOptions() throws SQLException { List<Option> ops=new ArrayList<>(); String sql="SELECT id_kategori_pemasukan,nama_kategori,is_spp FROM kategori_pemasukan ORDER BY nama_kategori"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql);ResultSet rs=ps.executeQuery()){ while(rs.next()) ops.add(new Option(rs.getInt(1), rs.getString(2)+(rs.getBoolean(3)?" (SPP)":""))); } return ops; }
    public boolean isSppCategory(int id) throws SQLException { try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement("SELECT is_spp FROM kategori_pemasukan WHERE id_kategori_pemasukan=?")){ ps.setInt(1,id); try(ResultSet rs=ps.executeQuery()){ return rs.next()&&rs.getBoolean(1); }} }
}
