// File: controller/PengeluaranController.java
package controller;

import java.sql.*;import java.util.ArrayList;import java.util.List;import model.Pengeluaran;import util.Koneksi;import util.Option;import util.SessionManager;

public class PengeluaranController {
    public List<Pengeluaran> getAll(java.sql.Date dari, java.sql.Date sampai)throws SQLException{ List<Pengeluaran> list=new ArrayList<>(); String sql="SELECT p.id_pengeluaran,p.tanggal,p.id_kategori_pengeluaran,p.nominal,p.keterangan,p.id_user_input,COALESCE(k.nama_kategori,'-') nama_kategori FROM pengeluaran p LEFT JOIN kategori_pengeluaran k ON p.id_kategori_pengeluaran=k.id_kategori_pengeluaran WHERE (? IS NULL OR p.tanggal>=?) AND (? IS NULL OR p.tanggal<=?) ORDER BY p.tanggal DESC,p.id_pengeluaran DESC"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ ps.setDate(1,dari);ps.setDate(2,dari);ps.setDate(3,sampai);ps.setDate(4,sampai); try(ResultSet rs=ps.executeQuery()){ while(rs.next()) list.add(new Pengeluaran(rs.getInt(1),rs.getDate(2),rs.getInt(3),rs.getDouble(4),rs.getString(5),rs.getInt(6),rs.getString(7))); }} return list; }
    public List<Pengeluaran> getAll()throws SQLException{return getAll(null,null);}    
    public void insert(Pengeluaran p)throws SQLException{ p.setIdUserInput(SessionManager.getInstance().getCurrentUserId()); String sql="INSERT INTO pengeluaran(tanggal,id_kategori_pengeluaran,nominal,keterangan,id_user_input) VALUES(?,?,?,?,?)"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ fill(ps,p); ps.setInt(5,p.getIdUserInput()); ps.executeUpdate(); } AuditLogger.log(p.getIdUserInput(),"INSERT PENGELUARAN",p.getKeterangan()+" nominal "+p.getNominal()); }
    public void update(Pengeluaran p)throws SQLException{ String sql="UPDATE pengeluaran SET tanggal=?,id_kategori_pengeluaran=?,nominal=?,keterangan=? WHERE id_pengeluaran=?"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ fill(ps,p); ps.setInt(5,p.getIdPengeluaran()); ps.executeUpdate(); } AuditLogger.log(SessionManager.getInstance().getCurrentUserId(),"UPDATE PENGELUARAN","ID "+p.getIdPengeluaran()); }
    public void delete(int id)throws SQLException{ try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM pengeluaran WHERE id_pengeluaran=?")){ ps.setInt(1,id); ps.executeUpdate(); } AuditLogger.log(SessionManager.getInstance().getCurrentUserId(),"DELETE PENGELUARAN","ID "+id); }
    private void fill(PreparedStatement ps,Pengeluaran p)throws SQLException{ ps.setDate(1,p.getTanggal()); ps.setInt(2,p.getIdKategoriPengeluaran()); ps.setDouble(3,p.getNominal()); ps.setString(4,p.getKeterangan()); }
    public List<Option> getKategoriOptions()throws SQLException{ List<Option> ops=new ArrayList<>(); try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement("SELECT id_kategori_pengeluaran,nama_kategori FROM kategori_pengeluaran ORDER BY nama_kategori");ResultSet rs=ps.executeQuery()){ while(rs.next()) ops.add(new Option(rs.getInt(1),rs.getString(2))); } return ops; }
}
