package controller;

import java.sql.*;import java.time.LocalDate;import java.util.*;import koneksi.Koneksi;import model.Pengeluaran;import util.UIUtils.Option;

public class PengeluaranController{private final Connection conn=Koneksi.getConnection();
 public List<Pengeluaran> getAll(String keyword)throws Exception{List<Pengeluaran> list=new ArrayList<>();String sql="SELECT p.*, k.nama_kategori FROM pengeluaran p LEFT JOIN kategori_pengeluaran k ON p.id_kategori_pengeluaran=k.id_kategori_pengeluaran WHERE COALESCE(k.nama_kategori,'') LIKE ? OR p.keterangan LIKE ? OR p.tanggal LIKE ? ORDER BY p.tanggal DESC,p.id_pengeluaran DESC";try(PreparedStatement ps=conn.prepareStatement(sql)){String k="%"+keyword+"%";ps.setString(1,k);ps.setString(2,k);ps.setString(3,k);try(ResultSet rs=ps.executeQuery()){while(rs.next())list.add(map(rs));}}return list;}
 public List<Pengeluaran> getByDate(LocalDate awal,LocalDate akhir)throws Exception{List<Pengeluaran> list=new ArrayList<>();String sql="SELECT p.*, k.nama_kategori FROM pengeluaran p LEFT JOIN kategori_pengeluaran k ON p.id_kategori_pengeluaran=k.id_kategori_pengeluaran WHERE p.tanggal BETWEEN ? AND ? ORDER BY p.tanggal,p.id_pengeluaran";try(PreparedStatement ps=conn.prepareStatement(sql)){ps.setDate(1,java.sql.Date.valueOf(awal));ps.setDate(2,java.sql.Date.valueOf(akhir));try(ResultSet rs=ps.executeQuery()){while(rs.next())list.add(map(rs));}}return list;}
 public double total()throws Exception{return total(null,null);} public double total(LocalDate awal,LocalDate akhir)throws Exception{String sql=awal==null?"SELECT COALESCE(SUM(nominal),0) total FROM pengeluaran":"SELECT COALESCE(SUM(nominal),0) total FROM pengeluaran WHERE tanggal BETWEEN ? AND ?";try(PreparedStatement ps=conn.prepareStatement(sql)){if(awal!=null){ps.setDate(1,java.sql.Date.valueOf(awal));ps.setDate(2,java.sql.Date.valueOf(akhir));}try(ResultSet rs=ps.executeQuery()){return rs.next()?rs.getDouble("total"):0;}}}
 public void insert(Pengeluaran p)throws Exception{try(PreparedStatement ps=conn.prepareStatement("INSERT INTO pengeluaran (tanggal,id_kategori_pengeluaran,nominal,keterangan) VALUES (?,?,?,?)")){fill(ps,p);ps.executeUpdate();}}
 public void update(Pengeluaran p)throws Exception{try(PreparedStatement ps=conn.prepareStatement("UPDATE pengeluaran SET tanggal=?, id_kategori_pengeluaran=?, nominal=?, keterangan=? WHERE id_pengeluaran=?")){fill(ps,p);ps.setInt(5,p.getIdPengeluaran());ps.executeUpdate();}}
 public void delete(int id)throws Exception{try(PreparedStatement ps=conn.prepareStatement("DELETE FROM pengeluaran WHERE id_pengeluaran=?")){ps.setInt(1,id);ps.executeUpdate();}}
 public List<Option> kategoriOptions()throws Exception{List<Option> list=new ArrayList<>();try(PreparedStatement ps=conn.prepareStatement("SELECT * FROM kategori_pengeluaran ORDER BY nama_kategori");ResultSet rs=ps.executeQuery()){while(rs.next())list.add(new Option(rs.getInt("id_kategori_pengeluaran"),rs.getString("nama_kategori")));}return list;}
 public List<Option> kategoriAll(String keyword)throws Exception{List<Option> list=new ArrayList<>();try(PreparedStatement ps=conn.prepareStatement("SELECT * FROM kategori_pengeluaran WHERE nama_kategori LIKE ? ORDER BY nama_kategori")){ps.setString(1,"%"+keyword+"%");try(ResultSet rs=ps.executeQuery()){while(rs.next())list.add(new Option(rs.getInt("id_kategori_pengeluaran"),rs.getString("nama_kategori")));}}return list;}
 public void insertKategori(String nama)throws Exception{try(PreparedStatement ps=conn.prepareStatement("INSERT INTO kategori_pengeluaran (nama_kategori) VALUES (?)")){ps.setString(1,nama);ps.executeUpdate();}}
 public void updateKategori(int id,String nama)throws Exception{try(PreparedStatement ps=conn.prepareStatement("UPDATE kategori_pengeluaran SET nama_kategori=? WHERE id_kategori_pengeluaran=?")){ps.setString(1,nama);ps.setInt(2,id);ps.executeUpdate();}}
 public void deleteKategori(int id)throws Exception{try(PreparedStatement ps=conn.prepareStatement("DELETE FROM kategori_pengeluaran WHERE id_kategori_pengeluaran=?")){ps.setInt(1,id);ps.executeUpdate();}}
 private void fill(PreparedStatement ps,Pengeluaran p)throws Exception{ps.setDate(1,java.sql.Date.valueOf(p.getTanggal()));ps.setInt(2,p.getIdKategoriPengeluaran());ps.setDouble(3,p.getNominal());ps.setString(4,p.getKeterangan());}
 private Pengeluaran map(ResultSet rs)throws Exception{return new Pengeluaran(rs.getInt("id_pengeluaran"),rs.getDate("tanggal").toLocalDate(),rs.getInt("id_kategori_pengeluaran"),rs.getString("nama_kategori"),rs.getDouble("nominal"),rs.getString("keterangan"));}}
