package form;

import controller.PengeluaranController;import java.awt.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import util.*;import util.UIUtils.Option;

public class KategoriPengeluaranFrame extends JPanel{private final PengeluaranController c=new PengeluaranController();private final JTextField nama=UIUtils.textField(18),cari=UIUtils.textField(18);private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Nama Kategori"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(m);private int id=0;
 public KategoriPengeluaranFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Kategori Pengeluaran");p.add(form(),BorderLayout.WEST);p.add(tabel(),BorderLayout.CENTER);add(p);load("");}
 private JPanel form(){JPanel p=UIUtils.card();p.setLayout(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,6,6,6);g.fill=GridBagConstraints.HORIZONTAL;g.gridx=0;g.gridy=0;p.add(new JLabel("Nama Kategori"),g);g.gridx=1;p.add(nama,g);JPanel b=UIUtils.toolbar();JButton tambah=UIUtils.secondaryButton("Tambah"),simpan=UIUtils.primaryButton("Simpan"),edit=UIUtils.secondaryButton("Edit"),hapus=UIUtils.dangerButton("Hapus");b.add(tambah);b.add(simpan);b.add(edit);b.add(hapus);g.gridx=0;g.gridy=1;g.gridwidth=2;p.add(b,g);tambah.addActionListener(e->clear());simpan.addActionListener(e->save());edit.addActionListener(e->update());hapus.addActionListener(e->delete());return p;}
 private JPanel tabel(){JPanel p=UIUtils.card();p.setLayout(new BorderLayout(8,8));JPanel t=UIUtils.toolbar();JButton refresh=UIUtils.secondaryButton("Refresh");t.add(new JLabel("Cari"));t.add(cari);t.add(refresh);p.add(t,BorderLayout.NORTH);p.add(UIUtils.tableScroll(table),BorderLayout.CENTER);UIUtils.bindRealtimeSearch(cari,m,table);refresh.addActionListener(e->{cari.setText("");load("");});table.getSelectionModel().addListSelectionListener(e->select());return p;}
 private void save(){if(!Validator.required("Nama kategori",nama.getText()))return;try{c.insertKategori(nama.getText().trim());clear();load("");}catch(Exception e){msg(e);}}private void update(){if(id==0||!Validator.required("Nama kategori",nama.getText()))return;try{c.updateKategori(id,nama.getText().trim());clear();load("");}catch(Exception e){msg(e);}}private void delete(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Hapus kategori?","Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{c.deleteKategori(id);clear();load("");}catch(Exception e){msg(e);}}
 private void load(String k){try{m.setRowCount(0);for(Option o:c.kategoriAll(k))m.addRow(new Object[]{o.getId(),o.toString()});}catch(Exception e){msg(e);}}private void select(){int r=table.getSelectedRow();if(r>=0){r=table.convertRowIndexToModel(r);id=(int)m.getValueAt(r,0);nama.setText(m.getValueAt(r,1).toString());}}private void clear(){id=0;nama.setText("");table.clearSelection();}private void msg(Exception e){JOptionPane.showMessageDialog(this,"Terjadi kesalahan: "+e.getMessage());}}
