package form;

import controller.KelasController;import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;import model.Kelas;import util.*;

public class KelasFrame extends JPanel{private final KelasController c=new KelasController();private final JTextField kode=UIUtils.textField(14),nama=UIUtils.textField(18),cari=UIUtils.textField(18);private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Kode Kelas","Nama Kelas"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(m);private int id=0;
 public KelasFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Data Kelas");p.add(form(),BorderLayout.WEST);p.add(tabel(),BorderLayout.CENTER);add(p);load("");}
 private JPanel form(){JPanel p=UIUtils.card();p.setLayout(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,6,6,6);g.fill=GridBagConstraints.HORIZONTAL;row(p,g,0,"Kode Kelas",kode);row(p,g,1,"Nama Kelas",nama);JPanel b=UIUtils.toolbar();JButton tambah=UIUtils.secondaryButton("Tambah"),simpan=UIUtils.primaryButton("Simpan"),edit=UIUtils.secondaryButton("Edit"),hapus=UIUtils.dangerButton("Hapus");b.add(tambah);b.add(simpan);b.add(edit);b.add(hapus);g.gridx=0;g.gridy=2;g.gridwidth=2;p.add(b,g);tambah.addActionListener(e->clear());simpan.addActionListener(e->save());edit.addActionListener(e->update());hapus.addActionListener(e->delete());return p;}
 private JPanel tabel(){JPanel p=UIUtils.card();p.setLayout(new BorderLayout(8,8));JPanel t=UIUtils.toolbar();JButton refresh=UIUtils.secondaryButton("Refresh");t.add(new JLabel("Cari"));t.add(cari);t.add(refresh);p.add(t,BorderLayout.NORTH);p.add(UIUtils.tableScroll(table),BorderLayout.CENTER);UIUtils.bindRealtimeSearch(cari,m,table);refresh.addActionListener(e->{cari.setText("");load("");});table.getSelectionModel().addListSelectionListener(e->select());return p;}
 private void row(JPanel p,GridBagConstraints g,int y,String l,Component comp){g.gridx=0;g.gridy=y;g.gridwidth=1;p.add(new JLabel(l),g);g.gridx=1;p.add(comp,g);}private Kelas val(){return new Kelas(id,kode.getText().trim(),nama.getText().trim());}private boolean valid(){return Validator.required("Kode kelas",kode.getText())&&Validator.required("Nama kelas",nama.getText());}
 private void save(){if(!valid())return;try{c.insert(val());clear();load("");JOptionPane.showMessageDialog(this,"Data kelas tersimpan.");}catch(Exception e){msg(e);}}private void update(){if(id==0||!valid())return;try{c.update(val());clear();load("");JOptionPane.showMessageDialog(this,"Data kelas diperbarui.");}catch(Exception e){msg(e);}}private void delete(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Hapus kelas terpilih?","Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{c.delete(id);clear();load("");}catch(Exception e){msg(e);}}
 private void load(String k){try{m.setRowCount(0);for(Kelas x:c.getAll(k))m.addRow(new Object[]{x.getIdKelas(),x.getKodeKelas(),x.getNamaKelas()});}catch(Exception e){msg(e);}}private void select(){int r=table.getSelectedRow();if(r>=0){r=table.convertRowIndexToModel(r);id=(int)m.getValueAt(r,0);kode.setText(m.getValueAt(r,1).toString());nama.setText(m.getValueAt(r,2).toString());}}private void clear(){id=0;kode.setText("");nama.setText("");table.clearSelection();}private void msg(Exception e){JOptionPane.showMessageDialog(this,"Terjadi kesalahan: "+e.getMessage());}}
