// File: form/LaporanForm.java
package form;

import java.awt.*;import java.sql.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import util.Koneksi;import util.UIUtils;

public class LaporanForm extends JPanel implements MainFrame.Refreshable{
    private final JTextField dari=UIUtils.createModernTextField("yyyy-mm-dd"), sampai=UIUtils.createModernTextField("yyyy-mm-dd"); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"Tanggal","Jenis","Kategori","Nominal","Keterangan"},0){public boolean isCellEditable(int r,int c){return false;}};
    public LaporanForm(){ setLayout(new BorderLayout(0,15)); setBackground(UIUtils.BACKGROUND); setBorder(BorderFactory.createEmptyBorder(15,15,15,15)); add(UIUtils.title("Laporan Keuangan"),BorderLayout.NORTH); JPanel filter=new JPanel(new FlowLayout(FlowLayout.LEFT)); filter.setOpaque(false); filter.add(UIUtils.label("Dari"));filter.add(dari);filter.add(UIUtils.label("Sampai"));filter.add(sampai); JButton tampil=UIUtils.createModernButton("Tampilkan",UIUtils.PRIMARY), cetak=UIUtils.createModernButton("Cetak/Export",UIUtils.SUCCESS); tampil.addActionListener(e->refreshData()); cetak.addActionListener(e->JOptionPane.showMessageDialog(this,"Data laporan siap diexport/cetak.")); filter.add(tampil);filter.add(cetak); add(filter,BorderLayout.WEST); add(UIUtils.modernScrollPane(new JTable(model)),BorderLayout.CENTER); refreshData(); }
    public void refreshData(){ model.setRowCount(0); String sql="SELECT tanggal,'Pemasukan' jenis,COALESCE(k.nama_kategori,'-') kategori,nominal,keterangan FROM pemasukan p LEFT JOIN kategori_pemasukan k ON p.id_kategori_pemasukan=k.id_kategori_pemasukan WHERE (? IS NULL OR tanggal>=?) AND (? IS NULL OR tanggal<=?) UNION ALL SELECT tanggal,'Pengeluaran',COALESCE(k.nama_kategori,'-'),nominal,keterangan FROM pengeluaran p LEFT JOIN kategori_pengeluaran k ON p.id_kategori_pengeluaran=k.id_kategori_pengeluaran WHERE (? IS NULL OR tanggal>=?) AND (? IS NULL OR tanggal<=?) ORDER BY tanggal"; try(Connection c=Koneksi.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ Date d=parse(dari.getText()), s=parse(sampai.getText()); ps.setDate(1,d);ps.setDate(2,d);ps.setDate(3,s);ps.setDate(4,s);ps.setDate(5,d);ps.setDate(6,d);ps.setDate(7,s);ps.setDate(8,s); try(ResultSet rs=ps.executeQuery()){ while(rs.next()) model.addRow(new Object[]{rs.getDate(1),rs.getString(2),rs.getString(3),UIUtils.formatRupiah(rs.getDouble(4)),rs.getString(5)}); }}catch(Exception ex){ UIUtils.showError(this,ex);} }
    private Date parse(String v){ try{return v==null||v.isBlank()?null:Date.valueOf(v.trim());}catch(Exception e){return null;} }
}
