package form;

import controller.*;import java.awt.*;import java.time.LocalDate;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.*;import util.*;

public class LaporanFrame extends JPanel{private final PemasukanController pc=new PemasukanController();private final PengeluaranController gc=new PengeluaranController();private final JTextField awal=UIUtils.textField(10),akhir=UIUtils.textField(10);private final JLabel ringkasan=new JLabel();private final DefaultTableModel m=new DefaultTableModel(new Object[]{"Tanggal","Jenis","Kategori","Pemasukan","Pengeluaran","Keterangan"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(m);
 public LaporanFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Laporan Keuangan");awal.setText(LocalDate.now().withDayOfMonth(1).toString());akhir.setText(LocalDate.now().toString());p.add(content(),BorderLayout.CENTER);add(p);load();}
 private JPanel content(){JPanel p=UIUtils.card();p.setLayout(new BorderLayout(8,8));JPanel f=UIUtils.toolbar();JButton tampil=UIUtils.primaryButton("Tampilkan"),pdf=UIUtils.secondaryButton("Export PDF"),cetak=UIUtils.secondaryButton("Print"),pdf2=UIUtils.secondaryButton("Cetak PDF");ringkasan.setFont(UIUtils.FONT_BOLD);f.add(new JLabel("Tanggal Awal"));f.add(awal);f.add(new JLabel("Tanggal Akhir"));f.add(akhir);f.add(tampil);f.add(pdf);f.add(pdf2);f.add(cetak);p.add(f,BorderLayout.NORTH);p.add(UIUtils.tableScroll(table),BorderLayout.CENTER);p.add(ringkasan,BorderLayout.SOUTH);tampil.addActionListener(e->load());pdf.addActionListener(e->UIUtils.exportTableToPdf(this,table,"Laporan Keuangan Kas Sekolah",ringkasan.getText()));pdf2.addActionListener(e->UIUtils.exportTableToPdf(this,table,"Laporan Keuangan Kas Sekolah",ringkasan.getText()));cetak.addActionListener(e->print());return p;}
 private void load(){LocalDate a=Validator.date("Tanggal awal",awal.getText()),b=Validator.date("Tanggal akhir",akhir.getText());if(a==null||b==null)return;if(b.isBefore(a)){JOptionPane.showMessageDialog(this,"Tanggal akhir tidak boleh sebelum tanggal awal.");return;}try{m.setRowCount(0);for(Pemasukan x:pc.getByDate(a,b))m.addRow(new Object[]{x.getTanggal(),"Pemasukan",x.getKategori(),UIUtils.rupiah(x.getNominal()),"-",x.getKeterangan()});for(Pengeluaran x:gc.getByDate(a,b))m.addRow(new Object[]{x.getTanggal(),"Pengeluaran",x.getKategori(),"-",UIUtils.rupiah(x.getNominal()),x.getKeterangan()});double masuk=pc.total(a,b),keluar=gc.total(a,b);ringkasan.setText("Total Pemasukan: "+UIUtils.rupiah(masuk)+"    Total Pengeluaran: "+UIUtils.rupiah(keluar)+"    Saldo Kas: "+UIUtils.rupiah(masuk-keluar));}catch(Exception e){JOptionPane.showMessageDialog(this,"Gagal memuat laporan: "+e.getMessage());}}
 private void print(){try{table.print(JTable.PrintMode.FIT_WIDTH,null,null);}catch(Exception e){JOptionPane.showMessageDialog(this,"Gagal print: "+e.getMessage());}}
}
