// File: form/PemasukanForm.java
package form;

import controller.PemasukanController;import controller.SiswaController;import java.awt.*;import java.sql.Date;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.Pemasukan;import util.Option;import util.UIUtils;

public class PemasukanForm extends JPanel implements MainFrame.Refreshable{
    private final PemasukanController controller=new PemasukanController(); private final SiswaController siswaController=new SiswaController(); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Tanggal","Siswa","Kategori","Nominal","Keterangan"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=new JTable(model); private final JTextField tanggal=UIUtils.createModernTextField("yyyy-mm-dd"), nominal=UIUtils.createModernTextField("Nominal"); private final JComboBox<Option> kategori=UIUtils.modernComboBox(), siswa=UIUtils.modernComboBox(); private final JTextArea ket=UIUtils.modernTextArea("Keterangan"); private int selectedId=0;
    public PemasukanForm(){ setLayout(new BorderLayout(0,15)); setBackground(UIUtils.BACKGROUND); setBorder(BorderFactory.createEmptyBorder(15,15,15,15)); add(UIUtils.title("Transaksi Pemasukan"),BorderLayout.NORTH); tanggal.setText(new Date(System.currentTimeMillis()).toString()); JPanel form=new JPanel(new GridLayout(0,2,8,8)); form.setOpaque(false); form.add(UIUtils.label("Tanggal"));form.add(tanggal); form.add(UIUtils.label("Kategori"));form.add(kategori); form.add(UIUtils.label("Siswa (khusus SPP)"));form.add(siswa); form.add(UIUtils.label("Nominal"));form.add(nominal); form.add(UIUtils.label("Keterangan"));form.add(new JScrollPane(ket)); JButton save=UIUtils.createModernButton("Simpan",UIUtils.SUCCESS), del=UIUtils.createModernButton("Hapus",UIUtils.DANGER), reset=UIUtils.createModernButton("Reset",UIUtils.PRIMARY); save.addActionListener(e->save()); del.addActionListener(e->delete()); reset.addActionListener(e->clear()); JPanel buttons=new JPanel(new FlowLayout(FlowLayout.LEFT)); buttons.setOpaque(false); buttons.add(save);buttons.add(del);buttons.add(reset); JPanel left=new JPanel(new BorderLayout()); left.setOpaque(false); left.add(form,BorderLayout.CENTER); left.add(buttons,BorderLayout.SOUTH); add(left,BorderLayout.WEST); add(UIUtils.modernScrollPane(table),BorderLayout.CENTER); kategori.addActionListener(e->toggleSiswa()); nominal.addFocusListener(new java.awt.event.FocusAdapter(){ public void focusLost(java.awt.event.FocusEvent e){ nominal.setText(UIUtils.formatRupiah(UIUtils.parseRupiah(nominal.getText()))); }}); table.getSelectionModel().addListSelectionListener(e->select()); refreshData(); }
    private void toggleSiswa(){ try{ Option op=(Option)kategori.getSelectedItem(); boolean spp=op!=null&&controller.isSppCategory(op.getId()); siswa.setEnabled(spp); if(!spp) siswa.setSelectedItem(null); }catch(Exception ignored){} }
    private void save(){ try{ Option ko=(Option)kategori.getSelectedItem(), so=(Option)siswa.getSelectedItem(); Pemasukan p=new Pemasukan(); p.setIdPemasukan(selectedId); p.setTanggal(Date.valueOf(tanggal.getText())); p.setIdKategoriPemasukan(ko.getId()); p.setIdSiswa(siswa.isEnabled()&&so!=null?so.getId():null); p.setNominal(UIUtils.parseRupiah(nominal.getText())); p.setKeterangan(ket.getText()); if(selectedId==0) controller.insert(p); else controller.update(p); clear(); refreshData(); }catch(Exception ex){ UIUtils.showError(this,ex);} }
    private void delete(){ try{ if(selectedId>0){ controller.delete(selectedId); clear(); refreshData(); }}catch(Exception ex){ UIUtils.showError(this,ex);} }
    private void select(){ int r=table.getSelectedRow(); if(r<0)return; selectedId=(int)model.getValueAt(r,0); tanggal.setText(String.valueOf(model.getValueAt(r,1))); nominal.setText(String.valueOf(model.getValueAt(r,4))); ket.setText(String.valueOf(model.getValueAt(r,5))); }
    private void clear(){ selectedId=0; tanggal.setText(new Date(System.currentTimeMillis()).toString()); nominal.setText(""); ket.setText(""); }
    public void refreshData(){ try{ kategori.removeAllItems(); for(Option o:controller.getKategoriOptions()) kategori.addItem(o); siswa.removeAllItems(); for(Option o:siswaController.getSiswaOptions()) siswa.addItem(o); toggleSiswa(); model.setRowCount(0); for(Pemasukan p:controller.getAll()) model.addRow(new Object[]{p.getIdPemasukan(),p.getTanggal(),p.getNamaSiswa(),p.getNamaKategori(),UIUtils.formatRupiah(p.getNominal()),p.getKeterangan()}); }catch(Exception ex){ UIUtils.showError(this,ex);} }
}
