package form;

import controller.PemasukanController;import java.awt.*;import java.time.LocalDate;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.Pemasukan;import util.*;import util.UIUtils.Option;

public class PemasukanFrame extends JPanel{private final PemasukanController c=new PemasukanController();private final JTextField tanggal=UIUtils.textField(12),nominal=UIUtils.textField(14),cari=UIUtils.textField(18);private final JComboBox<Option> kategori=new JComboBox<>();private final JTextArea ket=new JTextArea(3,18);private final JLabel total=new JLabel();private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Tanggal","ID Kategori","Kategori","Nominal","Keterangan"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(m);private int id=0;
 public PemasukanFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Pemasukan Kas");tanggal.setText(LocalDate.now().toString());p.add(form(),BorderLayout.WEST);p.add(tabel(),BorderLayout.CENTER);add(p);loadKategori();load("");}
 private JPanel form(){JPanel p=UIUtils.card();p.setLayout(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,6,6,6);g.fill=GridBagConstraints.HORIZONTAL;row(p,g,0,"Tanggal",tanggal);row(p,g,1,"Kategori",kategori);row(p,g,2,"Nominal",nominal);row(p,g,3,"Keterangan",new JScrollPane(ket));JPanel b=UIUtils.toolbar();JButton tambah=UIUtils.secondaryButton("Tambah"),simpan=UIUtils.primaryButton("Simpan"),edit=UIUtils.secondaryButton("Edit"),hapus=UIUtils.dangerButton("Hapus");b.add(tambah);b.add(simpan);b.add(edit);b.add(hapus);g.gridx=0;g.gridy=4;g.gridwidth=2;p.add(b,g);tambah.addActionListener(e->clear());simpan.addActionListener(e->save());edit.addActionListener(e->update());hapus.addActionListener(e->delete());return p;}
 private JPanel tabel(){JPanel p=UIUtils.card();p.setLayout(new BorderLayout(8,8));JPanel t=UIUtils.toolbar();JButton refresh=UIUtils.secondaryButton("Refresh");total.setFont(UIUtils.FONT_BOLD);t.add(new JLabel("Cari"));t.add(cari);t.add(refresh);t.add(total);p.add(t,BorderLayout.NORTH);p.add(UIUtils.tableScroll(table),BorderLayout.CENTER);UIUtils.bindRealtimeSearch(cari,m,table);refresh.addActionListener(e->{loadKategori();load("");cari.setText("");});table.getSelectionModel().addListSelectionListener(e->select());return p;}
 private void row(JPanel p,GridBagConstraints g,int y,String l,Component comp){g.gridx=0;g.gridy=y;g.gridwidth=1;p.add(new JLabel(l),g);g.gridx=1;p.add(comp,g);}private void loadKategori(){try{kategori.removeAllItems();for(Option o:c.kategoriOptions())kategori.addItem(o);}catch(Exception e){msg(e);}}private Pemasukan val(){Option o=(Option)kategori.getSelectedItem();return new Pemasukan(id,Validator.date("Tanggal",tanggal.getText()),o==null?0:o.getId(),"",Validator.money("Nominal",nominal.getText()),ket.getText().trim());}private boolean valid(Pemasukan p){return p.getTanggal()!=null&&p.getNominal()>=0&&kategori.getSelectedItem()!=null;}
 private void save(){Pemasukan p=val();if(!valid(p))return;try{c.insert(p);clear();load("");}catch(Exception e){msg(e);}}private void update(){Pemasukan p=val();if(id==0||!valid(p))return;try{c.update(p);clear();load("");}catch(Exception e){msg(e);}}private void delete(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Hapus pemasukan?","Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{c.delete(id);clear();load("");}catch(Exception e){msg(e);}}
 private void load(String k){try{m.setRowCount(0);for(Pemasukan p:c.getAll(k))m.addRow(new Object[]{p.getIdPemasukan(),p.getTanggal(),p.getIdKategoriPemasukan(),p.getKategori(),UIUtils.rupiah(p.getNominal()),p.getKeterangan()});total.setText("Total: "+UIUtils.rupiah(c.total()));}catch(Exception e){msg(e);}}private void select(){int r=table.getSelectedRow();if(r>=0){r=table.convertRowIndexToModel(r);id=(int)m.getValueAt(r,0);tanggal.setText(m.getValueAt(r,1).toString());int kid=(int)m.getValueAt(r,2);for(int i=0;i<kategori.getItemCount();i++)if(kategori.getItemAt(i).getId()==kid)kategori.setSelectedIndex(i);nominal.setText(m.getValueAt(r,4).toString().replace("Rp","").replace(" ","").replace(".","").replace(",00","").trim());ket.setText(String.valueOf(m.getValueAt(r,5)));}}private void clear(){id=0;tanggal.setText(LocalDate.now().toString());if(kategori.getItemCount()>0)kategori.setSelectedIndex(0);nominal.setText("");ket.setText("");table.clearSelection();}private void msg(Exception e){JOptionPane.showMessageDialog(this,"Terjadi kesalahan: "+e.getMessage());}}
