package form;

import controller.PengaturanController;import java.awt.*;import java.io.File;import javax.swing.*;import model.Pengaturan;import util.*;

public class PengaturanFrame extends JPanel{private final PengaturanController c=new PengaturanController();private final JTextField nama=UIUtils.textField(25),telp=UIUtils.textField(18),email=UIUtils.textField(18),kepala=UIUtils.textField(18),bendahara=UIUtils.textField(18),logo=UIUtils.textField(18);private final JTextArea alamat=new JTextArea(4,25);private int id=0;
 public PengaturanFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Pengaturan Profil Sekolah");p.add(form(),BorderLayout.CENTER);add(p);load();}
 private JPanel form(){JPanel p=UIUtils.card();p.setLayout(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(7,7,7,7);g.fill=GridBagConstraints.HORIZONTAL;row(p,g,0,"Nama Sekolah",nama);row(p,g,1,"Alamat",new JScrollPane(alamat));row(p,g,2,"Telepon",telp);row(p,g,3,"Email",email);row(p,g,4,"Nama Kepala Sekolah",kepala);row(p,g,5,"Nama Bendahara",bendahara);JPanel lp=UIUtils.toolbar();JButton pilih=UIUtils.secondaryButton("Pilih Logo");lp.add(logo);lp.add(pilih);row(p,g,6,"Logo Sekolah",lp);JButton simpan=UIUtils.primaryButton("Simpan");g.gridx=1;g.gridy=7;p.add(simpan,g);pilih.addActionListener(e->pilihLogo());simpan.addActionListener(e->save());return p;}
 private void row(JPanel p,GridBagConstraints g,int y,String l,Component comp){g.gridx=0;g.gridy=y;g.gridwidth=1;p.add(new JLabel(l),g);g.gridx=1;p.add(comp,g);}private void load(){try{Pengaturan x=c.get();id=x.getIdPengaturan();nama.setText(x.getNamaSekolah());alamat.setText(x.getAlamat());telp.setText(x.getTelepon());email.setText(x.getEmail());kepala.setText(x.getKepalaSekolah());bendahara.setText(x.getBendahara());logo.setText(x.getLogoPath());}catch(Exception e){msg(e);}}
 private void pilihLogo(){JFileChooser fc=new JFileChooser();if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)logo.setText(fc.getSelectedFile().getAbsolutePath());}
 private void save(){if(!Validator.required("Nama sekolah",nama.getText()))return;try{c.save(new Pengaturan(id,nama.getText().trim(),alamat.getText().trim(),telp.getText().trim(),email.getText().trim(),kepala.getText().trim(),bendahara.getText().trim(),logo.getText().trim()));JOptionPane.showMessageDialog(this,"Pengaturan tersimpan.");load();}catch(Exception e){msg(e);}}private void msg(Exception e){JOptionPane.showMessageDialog(this,"Terjadi kesalahan: "+e.getMessage());}}
