// File: form/SiswaForm.java
package form;

import controller.SiswaController;import java.awt.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.Siswa;import util.Option;import util.UIUtils;

public class SiswaForm extends JPanel implements MainFrame.Refreshable{
    private final SiswaController controller=new SiswaController(); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","NIS","Nama","Kelas","JK","Alamat"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=new JTable(model); private final JTextField nis=UIUtils.createModernTextField("NIS"), nama=UIUtils.createModernTextField("Nama Siswa"); private final JComboBox<Option> kelas=UIUtils.modernComboBox(); private final JComboBox<String> jk=new JComboBox<>(new String[]{"Laki-laki","Perempuan"}); private final JTextArea alamat=UIUtils.modernTextArea("Alamat"); private int selectedId=0;
    public SiswaForm(){ setLayout(new BorderLayout(0,15)); setBackground(UIUtils.BACKGROUND); setBorder(BorderFactory.createEmptyBorder(15,15,15,15)); add(UIUtils.title("Data Master - Siswa"),BorderLayout.NORTH); JPanel form=new JPanel(new GridLayout(0,2,8,8)); form.setOpaque(false); form.add(UIUtils.label("NIS"));form.add(nis);form.add(UIUtils.label("Nama"));form.add(nama);form.add(UIUtils.label("Kelas"));form.add(kelas);form.add(UIUtils.label("Jenis Kelamin"));form.add(jk);form.add(UIUtils.label("Alamat"));form.add(new JScrollPane(alamat)); JButton save=UIUtils.createModernButton("Simpan",UIUtils.SUCCESS), del=UIUtils.createModernButton("Hapus",UIUtils.DANGER), reset=UIUtils.createModernButton("Reset",UIUtils.PRIMARY); save.addActionListener(e->save()); del.addActionListener(e->delete()); reset.addActionListener(e->clear()); JPanel buttons=new JPanel(new FlowLayout(FlowLayout.LEFT)); buttons.setOpaque(false); buttons.add(save);buttons.add(del);buttons.add(reset); JPanel top=new JPanel(new BorderLayout()); top.setOpaque(false); top.add(form,BorderLayout.CENTER); top.add(buttons,BorderLayout.SOUTH); add(top,BorderLayout.WEST); add(UIUtils.modernScrollPane(table),BorderLayout.CENTER); table.getSelectionModel().addListSelectionListener(e->select()); refreshData(); }
    private void save(){ try{ Option op=(Option)kelas.getSelectedItem(); Siswa s=new Siswa(selectedId,nis.getText(),nama.getText(),op==null?0:op.getId(),op==null?"":op.getText(),(String)jk.getSelectedItem(),alamat.getText()); if(selectedId==0) controller.insert(s); else controller.update(s); clear(); refreshData(); }catch(Exception ex){ UIUtils.showError(this,ex);} }
    private void delete(){ try{ if(selectedId>0){ controller.delete(selectedId); clear(); refreshData(); }}catch(Exception ex){ UIUtils.showError(this,ex);} }
    private void select(){ int r=table.getSelectedRow(); if(r<0)return; selectedId=(int)model.getValueAt(r,0); nis.setText(String.valueOf(model.getValueAt(r,1))); nama.setText(String.valueOf(model.getValueAt(r,2))); jk.setSelectedItem(String.valueOf(model.getValueAt(r,4))); alamat.setText(String.valueOf(model.getValueAt(r,5))); }
    private void clear(){ selectedId=0; nis.setText("");nama.setText("");alamat.setText(""); }
    public void refreshData(){ try{ kelas.removeAllItems(); for(Option o:controller.getKelasOptions()) kelas.addItem(o); model.setRowCount(0); for(Siswa s:controller.getAll()) model.addRow(new Object[]{s.getIdSiswa(),s.getNis(),s.getNamaSiswa(),s.getNamaKelas(),s.getJenisKelamin(),s.getAlamat()}); }catch(Exception ex){ UIUtils.showError(this,ex);} }
}
