package form;

import controller.*;import java.awt.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.Siswa;import util.*;import util.UIUtils.Option;

public class SiswaFrame extends JPanel{private final SiswaController c=new SiswaController();private final KelasController kc=new KelasController();private final JTextField nis=UIUtils.textField(14),nama=UIUtils.textField(18),cari=UIUtils.textField(18);private final JComboBox<Option> kelas=new JComboBox<>();private final JComboBox<String> jk=new JComboBox<>(new String[]{"Laki-laki","Perempuan"});private final JTextArea alamat=new JTextArea(3,18);private final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","NIS","Nama Siswa","ID Kelas","Kelas","Jenis Kelamin","Alamat"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(m);private int id=0;
 public SiswaFrame(){setLayout(new BorderLayout());JPanel p=UIUtils.page("Data Siswa");p.add(form(),BorderLayout.WEST);p.add(tabel(),BorderLayout.CENTER);add(p);loadKelas();load("");}
 private JPanel form(){JPanel p=UIUtils.card();p.setLayout(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,6,6,6);g.fill=GridBagConstraints.HORIZONTAL;row(p,g,0,"NIS",nis);row(p,g,1,"Nama Siswa",nama);row(p,g,2,"Kelas",kelas);row(p,g,3,"Jenis Kelamin",jk);row(p,g,4,"Alamat",new JScrollPane(alamat));JPanel b=UIUtils.toolbar();JButton tambah=UIUtils.secondaryButton("Tambah"),simpan=UIUtils.primaryButton("Simpan"),edit=UIUtils.secondaryButton("Edit"),hapus=UIUtils.dangerButton("Hapus");b.add(tambah);b.add(simpan);b.add(edit);b.add(hapus);g.gridx=0;g.gridy=5;g.gridwidth=2;p.add(b,g);tambah.addActionListener(e->clear());simpan.addActionListener(e->save());edit.addActionListener(e->update());hapus.addActionListener(e->delete());return p;}
 private JPanel tabel(){JPanel p=UIUtils.card();p.setLayout(new BorderLayout(8,8));JPanel t=UIUtils.toolbar();JButton refresh=UIUtils.secondaryButton("Refresh");t.add(new JLabel("Cari"));t.add(cari);t.add(refresh);p.add(t,BorderLayout.NORTH);p.add(UIUtils.tableScroll(table),BorderLayout.CENTER);UIUtils.bindRealtimeSearch(cari,m,table);refresh.addActionListener(e->{loadKelas();load("");cari.setText("");});table.getSelectionModel().addListSelectionListener(e->select());return p;}
 private void row(JPanel p,GridBagConstraints g,int y,String l,Component comp){g.gridx=0;g.gridy=y;g.gridwidth=1;p.add(new JLabel(l),g);g.gridx=1;p.add(comp,g);}private void loadKelas(){try{kelas.removeAllItems();for(Option o:kc.options())kelas.addItem(o);}catch(Exception e){msg(e);}}private Siswa val(){Option o=(Option)kelas.getSelectedItem();return new Siswa(id,nis.getText().trim(),nama.getText().trim(),o==null?0:o.getId(),"","",jk.getSelectedItem().toString(),alamat.getText().trim());}private boolean valid(){return Validator.required("NIS",nis.getText())&&Validator.required("Nama siswa",nama.getText())&&kelas.getSelectedItem()!=null;}
 private void save(){if(!valid())return;try{c.insert(val());clear();load("");JOptionPane.showMessageDialog(this,"Data siswa tersimpan.");}catch(Exception e){msg(e);}}private void update(){if(id==0||!valid())return;try{c.update(val());clear();load("");JOptionPane.showMessageDialog(this,"Data siswa diperbarui.");}catch(Exception e){msg(e);}}private void delete(){if(id==0)return;if(JOptionPane.showConfirmDialog(this,"Hapus siswa terpilih?","Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{c.delete(id);clear();load("");}catch(Exception e){msg(e);}}
 private void load(String k){try{m.setRowCount(0);for(Siswa s:c.getAll(k))m.addRow(new Object[]{s.getIdSiswa(),s.getNis(),s.getNamaSiswa(),s.getIdKelas(),s.getKodeKelas()+" - "+s.getNamaKelas(),s.getJenisKelamin(),s.getAlamat()});}catch(Exception e){msg(e);}}private void select(){int r=table.getSelectedRow();if(r>=0){r=table.convertRowIndexToModel(r);id=(int)m.getValueAt(r,0);nis.setText(m.getValueAt(r,1).toString());nama.setText(m.getValueAt(r,2).toString());int idK=(int)m.getValueAt(r,3);for(int i=0;i<kelas.getItemCount();i++)if(kelas.getItemAt(i).getId()==idK)kelas.setSelectedIndex(i);jk.setSelectedItem(m.getValueAt(r,5).toString());alamat.setText(String.valueOf(m.getValueAt(r,6)));}}private void clear(){id=0;nis.setText("");nama.setText("");if(kelas.getItemCount()>0)kelas.setSelectedIndex(0);jk.setSelectedIndex(0);alamat.setText("");table.clearSelection();}private void msg(Exception e){JOptionPane.showMessageDialog(this,"Terjadi kesalahan: "+e.getMessage());}}
