// File: form/TabunganForm.java
package form;

import controller.SiswaController;import controller.TabunganController;import java.awt.*;import java.sql.Date;import javax.swing.*;import javax.swing.table.DefaultTableModel;import model.Tabungan;import util.Option;import util.UIUtils;

public class TabunganForm extends JPanel implements MainFrame.Refreshable{
    private final TabunganController controller=new TabunganController(); private final SiswaController siswaController=new SiswaController(); private final JComboBox<Option> siswa=UIUtils.modernComboBox(); private final JRadioButton setor=new JRadioButton("Setor",true), tarik=new JRadioButton("Tarik"); private final JTextField nominal=UIUtils.createModernTextField("Nominal"); private final JTextArea ket=UIUtils.modernTextArea("Keterangan"); private final JLabel saldo=new JLabel(UIUtils.formatRupiah(0)); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"Tanggal","Jenis","Nominal","Keterangan"},0){public boolean isCellEditable(int r,int c){return false;}};
    public TabunganForm(){ setLayout(new BorderLayout(0,15)); setBackground(UIUtils.BACKGROUND); setBorder(BorderFactory.createEmptyBorder(15,15,15,15)); add(UIUtils.title("Tabungan Siswa"),BorderLayout.NORTH); ButtonGroup bg=new ButtonGroup(); bg.add(setor); bg.add(tarik); JPanel form=new JPanel(new GridLayout(0,2,8,8)); form.setOpaque(false); form.add(UIUtils.label("Siswa"));form.add(siswa); form.add(UIUtils.label("Saldo Terakhir")); saldo.setFont(new Font("SansSerif",Font.BOLD,18)); form.add(saldo); form.add(UIUtils.label("Jenis")); JPanel r=new JPanel(new FlowLayout(FlowLayout.LEFT)); r.setOpaque(false); r.add(setor);r.add(tarik); form.add(r); form.add(UIUtils.label("Nominal"));form.add(nominal); form.add(UIUtils.label("Keterangan"));form.add(new JScrollPane(ket)); JButton simpan=UIUtils.createModernButton("Simpan Mutasi",UIUtils.SUCCESS); simpan.addActionListener(e->save()); JPanel left=new JPanel(new BorderLayout()); left.setOpaque(false); left.add(form,BorderLayout.CENTER); left.add(simpan,BorderLayout.SOUTH); add(left,BorderLayout.WEST); add(UIUtils.modernScrollPane(new JTable(model)),BorderLayout.CENTER); siswa.addActionListener(e->loadMutasi()); refreshData(); }
    private void save(){ try{ Option op=(Option)siswa.getSelectedItem(); if(op==null)return; Tabungan t=new Tabungan(); t.setIdSiswa(op.getId()); t.setTanggal(new Date(System.currentTimeMillis())); t.setNominal(UIUtils.parseRupiah(nominal.getText())); t.setKeterangan(ket.getText()); if(setor.isSelected()) controller.setor(t); else controller.tarik(t); nominal.setText(""); ket.setText(""); loadMutasi(); }catch(Exception ex){ UIUtils.showError(this,ex);} }
    private void loadMutasi(){ try{ Option op=(Option)siswa.getSelectedItem(); if(op==null)return; saldo.setText(UIUtils.formatRupiah(controller.getSaldo(op.getId()))); model.setRowCount(0); for(Tabungan t:controller.getMutasiBySiswa(op.getId())) model.addRow(new Object[]{t.getTanggal(),t.getJenis(),UIUtils.formatRupiah(t.getNominal()),t.getKeterangan()}); }catch(Exception ex){ UIUtils.showError(this,ex);} }
    public void refreshData(){ try{ siswa.removeAllItems(); for(Option o:siswaController.getSiswaOptions()) siswa.addItem(o); loadMutasi(); }catch(Exception ex){ UIUtils.showError(this,ex);} }
}
